# @package _global_
defaults:
  - wandb: defaults
  - _self_

# Data
category_name: "Clothing_Shoes_and_Jewelry" # Toys_and_Games/Clothing_Shoes_and_Jewelry/Home_and_Kitchen
data_dir: /Users/kbibas/datasets/fbt_research/data/final

method: "gan" # gan/dcf/pcomp

# Model
img_encoder_output_dim: 16
category_emb_size: 8
price_emb_size: 8

# Optimization
dropout_rate: 0.0
weight_decay: 1e-4
gradient_clip_val: 1.0
epochs: 100
lr: 0.01
milestones: [15, 60]
batch_size: 512
num_workers: 4
is_autoecoder_detach: false

# Triplet
triplet_weight: 1.0
triplet_loss_margin: 0.2
hard_negative: true

# Discriminator
discriminator_weight: 0.3
clf_weight: 0.03

# Cycle
cycle_weight: 1.0
cycle_weight_labeled_pairs: 0.5

# P comp
epsilon: 0.1
lamb: 0.3

# Evaluation
check_val_every_n_epoch: 4
top_k: [1, 3, 5, 10]
seed: 1234

note: ""

hydra:
  job:
    chdir: True
  run:
    dir: /Users/kbibas/code/fbt_research/outputs/train${note}_${method}_${category_name}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: /Users/kbibas/code/fbt_research/outputs/
    subdir: train_${method}_${category_name}_${now:%Y%m%d_%H%M%S}_${hydra.job.num}
