program: main_execute_train.py
method: bayes
metric:
  name: retrieval_metrics/ndcg.max
  goal: maximize
parameters:
  cycle_weight:
    distribution: uniform
    min: 0.0
    max: 1.0
  clf_weight:
    distribution: uniform
    min: 0.0
    max: 1.0
  discriminator_weight:
    distribution: uniform
    min: 0.0
    max: 1.0

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
